repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
      - id: shellcheck
      - id: packer-validate

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.56.0
  hooks:
    - id: terraform_docs
    - id: infracost_breakdown

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    # Git style
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-vcs-permalinks
    - id: forbid-new-submodules
    - id: no-commit-to-branch

    # Common errors
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-yaml
    - id: check-merge-conflict
    - id: check-executables-have-shebangs

    # Cross platform
    - id: check-case-conflict
    - id: mixed-line-ending
      args: [--fix=lf]

    # Security
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
    - id: detect-private-key